name: Push File

on: [pull_request]

env:
  sha: $GITHUB_SHA
  user_email: '${{ secrets.REPOSITORY_EMAIL }}'
  user_name: '${{ secrets.REPOSITORY_USERNAME }}'
  destination_repo: ${{ secrets.REPOSITORY_RELEASE_TEST }}

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Mark test file
        run: |-
          echo $GITHUB_SHA > test02.md
          echo $GITHUB_SHA > test03.md
          echo $GITHUB_SHA > test04.md

      - name: Ignore unchanged file
        uses: ./
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: "test01.md"
          destination_repo: "${{ env.destination_repo }}"
          user_email: "${{ env.user_email }}"
          user_name: "${{ env.user_name }}"

      - name: Push changed file
        uses: ./
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: "test02.md"
          destination_repo: "${{ env.destination_repo }}"
          user_email: "${{ env.user_email }}"
          user_name: "${{ env.user_name }}"

      - name: Check custom commit message
        uses: ./
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: "test03.md"
          destination_repo: "${{ env.destination_repo }}"
          user_email: "${{ env.user_email }}"
          user_name: "${{ env.user_name }}"
          commit_message: "A custom message."

      - name: Check rsync runs
        uses: ./
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: "test04.md"
          destination_repo: "${{ env.destination_repo }}"
          user_email: "${{ env.user_email }}"
          user_name: "${{ env.user_name }}"
          use_rsync: "true"

      - name: Push renamed file
        uses: ./
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: "test02.md"
          destination_repo: "${{ env.destination_repo }}"
          user_email: "${{ env.user_email }}"
          user_name: "${{ env.user_name }}"
          rename: "test02_rename.md"
